name: iOS CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: macos-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install SwiftLint
        run: brew install swiftlint

      - name: Run SwiftLint
        run: swiftlint --strict

      - name: Select Xcode
        run: sudo xcode-select -switch /Applications/Xcode.app

      - name: Boot Simulator
        run: xcrun simctl boot "iPhone 16" || true

      - name: Run Unit Tests
        run: |
          xcodebuild test \
          -project FirstCICDApp.xcodeproj \
          -scheme FirstCICDApp \
          -destination 'platform=iOS Simulator,name=iPhone 16' \
          -only-testing:FirstCICDAppTests \
          -parallel-testing-enabled YES \
          CODE_SIGNING_ALLOWED=NO \
          -quiet

      - name: Build Archive (No Signing)
        run: |
          xcodebuild archive \
          -project FirstCICDApp.xcodeproj \
          -scheme FirstCICDApp \
          -configuration Release \
          -archivePath $PWD/build/FirstCICDApp.xcarchive \
          -destination 'generic/platform=iOS' \
          CODE_SIGNING_ALLOWED=NO

      - name: Package App
        run: |
          cd build/FirstCICDApp.xcarchive/Products/Applications
          zip -r FirstCICDApp.zip FirstCICDApp.app

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: FirstCICDApp-build
          path: build/FirstCICDApp.xcarchive/Products/Applications/FirstCICDApp.zip
