name: iOS CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: macos-latest

    steps:

      - uses: actions/checkout@v4

      - name: Install SwiftLint
        run: brew install swiftlint

      - name: Run SwiftLint
        run: swiftlint --strict

      - name: Run Unit Tests
        run: |
          xcodebuild test \
          -project FirstCICDApp.xcodeproj \
          -scheme FirstCICDApp \
          -destination 'platform=iOS Simulator,name=iPhone 16'

      - name: Build Archive
        run: |
          xcodebuild archive \
          -project FirstCICDApp.xcodeproj \
          -scheme FirstCICDApp \
          -configuration Release \
          -archivePath $PWD/build/FirstCICDApp.xcarchive \
          -destination 'generic/platform=iOS' \
          CODE_SIGNING_ALLOWED=NO

      - name: Export IPA
        run: |
          xcodebuild -exportArchive \
          -archivePath $PWD/build/FirstCICDApp.xcarchive \
          -exportOptionsPlist ExportOptions.plist \
          -exportPath $PWD/build \
          CODE_SIGNING_ALLOWED=NO

      - name: Upload IPA Artifact
        uses: actions/upload-artifact@v4
        with:
          name: FirstCICDApp-ipa
          path: build/*.ipa
